
spring:
  profiles:
    active: dev
  application:
    name: xypp
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xxpp?serverTimezone=Asia/Shanghai
    username: xxpp
    password: 123456
  # session 失效时间（分钟）
  session:
    timeout: 86400
    store-type: redis

